import Head from 'next/head';
//import { trpc } from '../utils/trpc';
import Navbar from './components/Navbar';
import type { NextPage } from 'next';
import { useSession } from 'next-auth/react';

const Home: NextPage = () => {
//  const etMsg = trpc.useQuery(['trpcRoute.etAPI']);

  const { data: session, status } = useSession();

  return (
    <section>
      <Head>
        <title>ET T3+</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar session={session} status={status} />

      <main id="TOP" className="h-screen bg-black text-white">
        <div className="flex place-content-center h-screen">
        <div className="flex place-content-center items-center">
          {/* {status === 'authenticated' && session && session.user && <p>Signed in as {session.user.email}</p>} */}

            <div className="flex flex-col">
              <div className="text-2xl text-center my-2"></div>
              <div className=" text-lg">

{/* 

                {etMsg.data ? (
                  <span className="mx-10">
                    <a href="https://et-dev.firstam.com">{etMsg.data.greeting}</a>
                  </span>
                ) : (
                  <span>Loading..</span>
                )}

 */}

              </div>

              <a href="#API">
                <div className="flex btn rounded-lg w-fit mx-auto mt-2 bg-black border-gray-500 hover:bg-gray-800 hover:border-gray-800">
                  GO LOW
                </div>
              </a>
            </div>
          </div>
          <div className="flex place-items-center mx-5">
            <ul>
              <li>
                <a href="https://nextjs.org" target={`_blank`}>
                  Next.js
                </a>
              </li>
              <li>
                <a href="https://prisma.io" target={`_blank`}>
                  Prisma
                </a>
              </li>
              <li>
                <a href="https://www.postgresql.org/" target={`_blank`}>
                  PostgreSQL
                </a>
              </li>
              <li>
                <a href="https://supabase.com/" target={`_blank`}>
                  Supabase
                </a>
              </li>
              <li>
                <a href="https://vercel.com" target={`_blank`}>
                  Vercel
                </a>
              </li>
              <li>
                <a href="https://trpc.io" target={`_blank`}>
                  tRPC
                </a>
              </li>
              <li>
                <a href="https://daisyui.com" target={`_blank`}>
                  Daisy UI
                </a>
              </li>
              <li>
                <a href="https://typescriptlang.org" target={`_blank`}>
                  TypeScript
                </a>
              </li>
              <li>
                <a href="https://tailwindcss.com" target={`_blank`}>
                  Tailwind
                </a>
              </li>
            </ul>
          </div>
        </div>
      </main>

      <main id="API" className="flex place-content-center h-screen">
        <div className="flex flex-col place-content-center items-center">

          <div className="text-6xl mx-5">
            BELOW IS HERE
          </div>
        <a href="#TOP">  
        <button className="btn btn-outline btn-accent w-96 my-4">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
          <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l7.5-7.5 7.5 7.5m-15 6l7.5-7.5 7.5 7.5" /></svg>
        </button>
        </a>
{/*           <ul>
            <li>
              <a href={'/api/helloworld'}>/helloworld</a>
            </li>
            <li>
              <a href={'/api/getUsers'}>/getUsers</a>
            </li>
            <li>
              <a href={'/api/createUser'}>/createUser</a>
            </li>
            <li>
              <a href={'/api/deleteUser'}>/deleteUser</a>
            </li>
            <li>
              <a href={'http://localhost:5555'}>/PrismaStudio</a>
            </li>
          </ul> */}
        </div>
      </main>

      <main className="flex place-content-center h-64">
        <footer className="footer footer-center p-10 bg-base-200 text-base-content rounded">
          <div className="grid grid-flow-col gap-4">
            <a className="link link-hover">About us</a> 
            <a className="link link-hover">Contact</a> 
            <a className="link link-hover">Jobs</a> 
            <a className="link link-hover">Marketing</a>
          </div> 
          <div>
            <div className="grid grid-flow-col gap-4">
              <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" className="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg></a> 
              <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" className="fill-current"><path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path></svg></a> 
              <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" className="fill-current"><path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path></svg></a>
            </div>
          </div> 
          <div>
            <p>Copyright © 2023 - All right reserved by GrowAGram.com Ltd.</p>
          </div>
        </footer>
      </main>

{/* 

      <div className="bg-black text-white text-center">
        {etMsg.data ? <p>{etMsg.data.greeting}</p> : <p>Loading..</p>}
      </div>

 */}

    </section>
  );
};

export default Home;
