import Head from 'next/head';
//import { trpc } from '../utils/trpc';
import Navbar from './components/Navbar';
import type { NextPage } from 'next';
import { useSession } from 'next-auth/react';

const Home: NextPage = () => {
//  const etMsg = trpc.useQuery(['trpcRoute.etAPI']);

  const { data: session, status } = useSession();

  return (
    <section>
      <Head>
        <title>ET T3+</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar session={session} status={status} />

      <main className="h-screen bg-black text-white">
        <div className="flex place-content-center h-screen">
        <div id="TOP" className="flex place-content-center items-center">
          {/* {status === 'authenticated' && session && session.user && <p>Signed in as {session.user.email}</p>} */}

            <div className="flex flex-col">
              <div className="text-2xl text-center my-2"></div>
              <div className=" text-lg">

{/* 

                {etMsg.data ? (
                  <span className="mx-10">
                    <a href="https://et-dev.firstam.com">{etMsg.data.greeting}</a>
                  </span>
                ) : (
                  <span>Loading..</span>
                )}

 */}

              </div>

              <a href="#API">
                <div className="flex btn rounded-lg w-fit mx-auto mt-2 bg-black border-gray-500 hover:bg-gray-800 hover:border-gray-800">
                  GO LOW
                </div>
              </a>
            </div>
          </div>
          <div className="flex place-items-center mx-5">
            <ul>
              <li>
                <a href="https://nextjs.org" target={`_blank`}>
                  Next.js
                </a>
              </li>
              <li>
                <a href="https://prisma.io" target={`_blank`}>
                  Prisma
                </a>
              </li>
              <li>
                <a href="https://www.postgresql.org/" target={`_blank`}>
                  PostgreSQL
                </a>
              </li>
              <li>
                <a href="https://supabase.com/" target={`_blank`}>
                  Supabase
                </a>
              </li>
              <li>
                <a href="https://vercel.com" target={`_blank`}>
                  Vercel
                </a>
              </li>
              <li>
                <a href="https://trpc.io" target={`_blank`}>
                  tRPC
                </a>
              </li>
              <li>
                <a href="https://daisyui.com" target={`_blank`}>
                  Daisy UI
                </a>
              </li>
              <li>
                <a href="https://typescriptlang.org" target={`_blank`}>
                  TypeScript
                </a>
              </li>
              <li>
                <a href="https://tailwindcss.com" target={`_blank`}>
                  Tailwind
                </a>
              </li>
            </ul>
          </div>
        </div>
      </main>

      <main className="flex place-content-center h-screen">
        <div className="flex flex-col place-content-center items-center">

          <div id="API" className="text-6xl mx-5">
            BELOW IS HERE
          </div>
        <a href="#TOP">  
        <button className="btn btn-outline btn-accent w-96 my-4">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
          <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l7.5-7.5 7.5 7.5m-15 6l7.5-7.5 7.5 7.5" /></svg>
        </button>
        </a>
{/*           <ul>
            <li>
              <a href={'/api/helloworld'}>/helloworld</a>
            </li>
            <li>
              <a href={'/api/getUsers'}>/getUsers</a>
            </li>
            <li>
              <a href={'/api/createUser'}>/createUser</a>
            </li>
            <li>
              <a href={'/api/deleteUser'}>/deleteUser</a>
            </li>
            <li>
              <a href={'http://localhost:5555'}>/PrismaStudio</a>
            </li>
          </ul> */}
        </div>
      </main>

{/* 

      <div className="bg-black text-white text-center">
        {etMsg.data ? <p>{etMsg.data.greeting}</p> : <p>Loading..</p>}
      </div>

 */}

    </section>
  );
};

export default Home;
