import Head from "next/head";
//import { trpc } from '../utils/trpc';
import type { NextPage } from "next";

const Home: NextPage = () => {
  //  const etMsg = trpc.useQuery(['trpcRoute.etAPI']);

  return (
    <section id="TOP">
      <Head>
        <title>ET T3+</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen bg-black text-white">
        <div className="flex h-screen place-content-center">
          <div className="flex place-content-center items-center">
            {/* {status === 'authenticated' && session && session.user && <p>Signed in as {session.user.email}</p>} */}

            <div className="flex flex-col">
              <div className="my-2 text-center text-2xl"></div>
              <div className=" text-lg">
                {/* 

                {etMsg.data ? (
                  <span className="mx-10">
                    <a href="https://et-dev.firstam.com">{etMsg.data.greeting}</a>
                  </span>
                ) : (
                  <span>Loading..</span>
                )}

 */}
              </div>

              <a href="#API">
                <div className="btn mx-auto mt-2 flex w-fit rounded-lg border-gray-500 bg-black hover:border-gray-800 hover:bg-gray-800">
                  GO LOW
                </div>
              </a>
            </div>
          </div>
          <div className="mx-5 flex place-items-center">
            <ul>
              <li>
                <a href="https://nextjs.org" target={`_blank`}>
                  Next.js
                </a>
              </li>
              <li>
                <a href="https://prisma.io" target={`_blank`}>
                  Prisma
                </a>
              </li>
              <li>
                <a href="https://www.postgresql.org/" target={`_blank`}>
                  PostgreSQL
                </a>
              </li>
              <li>
                <a href="https://supabase.com/" target={`_blank`}>
                  Supabase
                </a>
              </li>
              <li>
                <a href="https://vercel.com" target={`_blank`}>
                  Vercel
                </a>
              </li>
              <li>
                <a href="https://trpc.io" target={`_blank`}>
                  tRPC
                </a>
              </li>
              <li>
                <a href="https://daisyui.com" target={`_blank`}>
                  Daisy UI
                </a>
              </li>
              <li>
                <a href="https://typescriptlang.org" target={`_blank`}>
                  TypeScript
                </a>
              </li>
              <li>
                <a href="https://tailwindcss.com" target={`_blank`}>
                  Tailwind
                </a>
              </li>
            </ul>
          </div>
        </div>
        <section id="API" className="flex h-screen place-content-center">
          <div className="flex flex-col place-content-center items-center">
            <div className="mx-5 text-6xl">BELOW IS HERE</div>
            <a href="#TOP">
              <button className="btn btn-outline btn-accent my-4 w-96">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="h-6 w-6"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M4.5 12.75l7.5-7.5 7.5 7.5m-15 6l7.5-7.5 7.5 7.5"
                  />
                </svg>
              </button>
            </a>
            {/*           <ul>
            <li>
              <a href={'/api/helloworld'}>/helloworld</a>
            </li>
            <li>
              <a href={'/api/getUsers'}>/getUsers</a>
            </li>
            <li>
              <a href={'/api/createUser'}>/createUser</a>
            </li>
            <li>
              <a href={'/api/deleteUser'}>/deleteUser</a>
            </li>
            <li>
              <a href={'http://localhost:5555'}>/PrismaStudio</a>
            </li>
          </ul> */}
          </div>
        </section>
      </main>
    </section>
  );
};

export default Home;
